// Auto-generated by Supabase CLI — NEVER hand-edit this file.
// Regenerate after every migration:
//   supabase gen types typescript --linked > src/types/supabase.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          name: string
          slug: string | null
          plan_status: 'trial' | 'active' | 'past_due' | 'cancelled'
          trial_ends_at: string | null
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          lock_window_days: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug?: string | null
          plan_status?: 'trial' | 'active' | 'past_due' | 'cancelled'
          trial_ends_at?: string | null
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          lock_window_days?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string | null
          plan_status?: 'trial' | 'active' | 'past_due' | 'cancelled'
          trial_ends_at?: string | null
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          lock_window_days?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          id: string
          tenant_id: string
          role: 'owner' | 'admin' | 'member'
          full_name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          tenant_id: string
          role?: 'owner' | 'admin' | 'member'
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          role?: 'owner' | 'admin' | 'member'
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'profiles_tenant_id_fkey'
            columns: ['tenant_id']
            referencedRelation: 'tenants'
            referencedColumns: ['id']
          },
        ]
      }
      clients: {
        Row: {
          id: string
          tenant_id: string
          created_by: string
          name: string
          email: string | null
          phone: string | null
          event_date: string | null
          venue: string | null
          guest_count: number | null
          budget: number | null
          pipeline_stage:
            | 'lead'
            | 'qualified'
            | 'proposal_sent'
            | 'revision'
            | 'booked'
            | 'in_fulfillment'
            | 'completed'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          created_by: string
          name: string
          email?: string | null
          phone?: string | null
          event_date?: string | null
          venue?: string | null
          guest_count?: number | null
          budget?: number | null
          pipeline_stage?:
            | 'lead'
            | 'qualified'
            | 'proposal_sent'
            | 'revision'
            | 'booked'
            | 'in_fulfillment'
            | 'completed'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          created_by?: string
          name?: string
          email?: string | null
          phone?: string | null
          event_date?: string | null
          venue?: string | null
          guest_count?: number | null
          budget?: number | null
          pipeline_stage?:
            | 'lead'
            | 'qualified'
            | 'proposal_sent'
            | 'revision'
            | 'booked'
            | 'in_fulfillment'
            | 'completed'
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'clients_tenant_id_fkey'
            columns: ['tenant_id']
            referencedRelation: 'tenants'
            referencedColumns: ['id']
          },
        ]
      }
      client_activities: {
        Row: {
          id: string
          tenant_id: string
          client_id: string
          logged_by: string
          activity_type: 'call' | 'meeting' | 'note' | 'task'
          summary: string
          note: string | null
          due_at: string | null
          task_status: 'open' | 'completed'
          completed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          client_id: string
          logged_by: string
          activity_type: 'call' | 'meeting' | 'note' | 'task'
          summary: string
          note?: string | null
          due_at?: string | null
          task_status?: 'open' | 'completed'
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          client_id?: string
          logged_by?: string
          activity_type?: 'call' | 'meeting' | 'note' | 'task'
          summary?: string
          note?: string | null
          due_at?: string | null
          task_status?: 'open' | 'completed'
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'client_activities_client_id_fkey'
            columns: ['client_id']
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'client_activities_tenant_id_fkey'
            columns: ['tenant_id']
            referencedRelation: 'tenants'
            referencedColumns: ['id']
          },
        ]
      }
      inventory_items: {
        Row: {
          id: string
          tenant_id: string
          created_by: string
          name: string
          category: 'flowers' | 'decor' | 'consumables'
          unit: string
          cost: number
          quantity_on_hand: number
          sku: string
          barcode_value: string | null
          is_unavailable: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          created_by: string
          name: string
          category: 'flowers' | 'decor' | 'consumables'
          unit: string
          cost?: number
          quantity_on_hand?: number
          sku: string
          barcode_value?: string | null
          is_unavailable?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          created_by?: string
          name?: string
          category?: 'flowers' | 'decor' | 'consumables'
          unit?: string
          cost?: number
          quantity_on_hand?: number
          sku?: string
          barcode_value?: string | null
          is_unavailable?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'inventory_items_tenant_id_fkey'
            columns: ['tenant_id']
            referencedRelation: 'tenants'
            referencedColumns: ['id']
          },
        ]
      }
      recipes: {
        Row: {
          id: string
          tenant_id: string
          created_by: string
          name: string
          event_type: string | null
          client_id: string | null
          recipe_tags: string[]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          created_by: string
          name: string
          event_type?: string | null
          client_id?: string | null
          recipe_tags?: string[]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          created_by?: string
          name?: string
          event_type?: string | null
          client_id?: string | null
          recipe_tags?: string[]
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'recipes_client_id_fkey'
            columns: ['client_id']
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'recipes_tenant_id_fkey'
            columns: ['tenant_id']
            referencedRelation: 'tenants'
            referencedColumns: ['id']
          },
        ]
      }
      events: {
        Row: {
          id: string
          tenant_id: string
          created_by: string
          name: string
          start_at: string
          end_at: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          created_by: string
          name: string
          start_at: string
          end_at: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          created_by?: string
          name?: string
          start_at?: string
          end_at?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'events_tenant_id_fkey'
            columns: ['tenant_id']
            referencedRelation: 'tenants'
            referencedColumns: ['id']
          },
        ]
      }
      inventory_allocations: {
        Row: {
          id: string
          tenant_id: string
          inventory_item_id: string
          event_id: string
          quantity_committed: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          inventory_item_id: string
          event_id: string
          quantity_committed: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          inventory_item_id?: string
          event_id?: string
          quantity_committed?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'inventory_allocations_event_id_fkey'
            columns: ['event_id']
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'inventory_allocations_inventory_item_id_fkey'
            columns: ['inventory_item_id']
            referencedRelation: 'inventory_items'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'inventory_allocations_tenant_id_fkey'
            columns: ['tenant_id']
            referencedRelation: 'tenants'
            referencedColumns: ['id']
          },
        ]
      }
      ai_jobs: {
        Row: {
          id: string
          tenant_id: string
          created_by: string
          source_type: 'image' | 'pinterest_url'
          source_payload: Json
          status: 'pending' | 'processing' | 'completed' | 'failed'
          result_payload: Json | null
          error_message: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          created_by: string
          source_type: 'image' | 'pinterest_url'
          source_payload?: Json
          status?: 'pending' | 'processing' | 'completed' | 'failed'
          result_payload?: Json | null
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          created_by?: string
          source_type?: 'image' | 'pinterest_url'
          source_payload?: Json
          status?: 'pending' | 'processing' | 'completed' | 'failed'
          result_payload?: Json | null
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'ai_jobs_tenant_id_fkey'
            columns: ['tenant_id']
            referencedRelation: 'tenants'
            referencedColumns: ['id']
          },
        ]
      }
      quotes: {
        Row: {
          id: string
          tenant_id: string
          created_by: string
          client_id: string | null
          title: string
          status: 'draft' | 'sent' | 'approved' | 'revision_requested' | 'locked'
          note: string | null
          discount_type: 'percent' | 'fixed' | null
          discount_value: number
          root_quote_id: string | null
          revision_number: number
          locked_at: string | null
          unlocked_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          created_by: string
          client_id?: string | null
          title?: string
          status?: 'draft' | 'sent' | 'approved' | 'revision_requested' | 'locked'
          note?: string | null
          discount_type?: 'percent' | 'fixed' | null
          discount_value?: number
          root_quote_id?: string | null
          revision_number?: number
          locked_at?: string | null
          unlocked_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          created_by?: string
          client_id?: string | null
          title?: string
          status?: 'draft' | 'sent' | 'approved' | 'revision_requested' | 'locked'
          note?: string | null
          discount_type?: 'percent' | 'fixed' | null
          discount_value?: number
          root_quote_id?: string | null
          revision_number?: number
          locked_at?: string | null
          unlocked_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'quotes_client_id_fkey'
            columns: ['client_id']
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'quotes_tenant_id_fkey'
            columns: ['tenant_id']
            referencedRelation: 'tenants'
            referencedColumns: ['id']
          },
        ]
      }
      quote_line_items: {
        Row: {
          id: string
          tenant_id: string
          quote_id: string
          inventory_item_id: string
          description: string
          quantity: number
          unit_cost_snapshot: number
          line_type: 'inventory' | 'custom' | 'discount'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          quote_id: string
          inventory_item_id: string
          description: string
          quantity?: number
          unit_cost_snapshot: number
          line_type?: 'inventory' | 'custom' | 'discount'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          quote_id?: string
          inventory_item_id?: string
          description?: string
          quantity?: number
          unit_cost_snapshot?: number
          line_type?: 'inventory' | 'custom' | 'discount'
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'quote_line_items_inventory_item_id_fkey'
            columns: ['inventory_item_id']
            referencedRelation: 'inventory_items'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'quote_line_items_quote_id_fkey'
            columns: ['quote_id']
            referencedRelation: 'quotes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'quote_line_items_tenant_id_fkey'
            columns: ['tenant_id']
            referencedRelation: 'tenants'
            referencedColumns: ['id']
          },
        ]
      }
      recipe_items: {
        Row: {
          id: string
          tenant_id: string
          recipe_id: string
          inventory_item_id: string
          stem_count: number
          quantity: number
          position: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          recipe_id: string
          inventory_item_id: string
          stem_count?: number
          quantity?: number
          position?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          recipe_id?: string
          inventory_item_id?: string
          stem_count?: number
          quantity?: number
          position?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'recipe_items_inventory_item_id_fkey'
            columns: ['inventory_item_id']
            referencedRelation: 'inventory_items'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'recipe_items_recipe_id_fkey'
            columns: ['recipe_id']
            referencedRelation: 'recipes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'recipe_items_tenant_id_fkey'
            columns: ['tenant_id']
            referencedRelation: 'tenants'
            referencedColumns: ['id']
          },
        ]
      }
      quote_audit_logs: {
        Row: {
          id: string
          tenant_id: string
          quote_id: string
          action_type: string
          action_payload: Json
          performed_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          quote_id: string
          action_type: string
          action_payload?: Json
          performed_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          quote_id?: string
          action_type?: string
          action_payload?: Json
          performed_by?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'quote_audit_logs_quote_id_fkey'
            columns: ['quote_id']
            referencedRelation: 'quotes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'quote_audit_logs_tenant_id_fkey'
            columns: ['tenant_id']
            referencedRelation: 'tenants'
            referencedColumns: ['id']
          },
        ]
      }
      quote_share_tokens: {
        Row: {
          id: string
          tenant_id: string
          quote_id: string
          client_id: string | null
          token: string
          expires_at: string
          consumed_at: string | null
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          quote_id: string
          client_id?: string | null
          token: string
          expires_at: string
          consumed_at?: string | null
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          quote_id?: string
          client_id?: string | null
          token?: string
          expires_at?: string
          consumed_at?: string | null
          created_by?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'quote_share_tokens_client_id_fkey'
            columns: ['client_id']
            referencedRelation: 'clients'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'quote_share_tokens_quote_id_fkey'
            columns: ['quote_id']
            referencedRelation: 'quotes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'quote_share_tokens_tenant_id_fkey'
            columns: ['tenant_id']
            referencedRelation: 'tenants'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
